settings:
  name: "StorageGRID 11.8"
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
sidebar:
  entries:
    - title: StorageGRID 11.8 Docs
      url: /index.html
    - title: Release notes
      url: "/release-notes/index.html"
    - title: Get started
      entries:
      - section: primer
      - section: network
      - title: Quick start for StorageGRID
        url: /primer/quick-start.html      
    - title: Install and upgrade
      entries:
      - section: rhel
      - section: ubuntu
      - section: vmware
      - section: upgrade
    - title: Configure and manage
      entries:
      - section: admin
      - section: ilm
      - section: harden
      - section: fabricpool
    - title: Use StorageGRID
      entries:
      - section: tenant
      - section: s3
      - section: swift
    - title: Monitor and troubleshoot
      entries:
      - section: monitor
      - section: troubleshoot
      - section: audit
    - section: expand
    - section: maintain
    - title: StorageGRID appliances
      url: /storagegrid-hardware.html    
    - title: Enable StorageGRID
      url: /storagegrid-enable.html
    - title: Earlier versions
      url: /earlier-versions.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: StorageGRID documentation
  repo: storagegrid-family