settings:
  name: "StorageGRID 11.8"
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
sidebar:
  entries:
    - title: StorageGRID 11.8 Docs
      url: /index.html
    - title: Release notes
      url: "/release-notes/index.html"
    - title: Get started
      url: "/landing-get-started/index.html"  
      entries:
      - section: primer
      - section: network
      - title: Quick start
        url: /quick-start.html      
    - title: Install and upgrade
      url: "/landing-install-upgrade/index.html"  
      entries:
      - title: Install appliances
        url: /storagegrid-hardware.html 
      - section: rhel
      - section: ubuntu
      - section: vmware
      - section: upgrade
      - title: Install StorageGRID hotfix
        url: "/maintain/storagegrid-hotfix-procedure.html"
    - title: Configure and manage
      url: "/landing-configure-manage/index.html"  
      entries:
      - section: admin
      - section: ilm
      - section: harden
      - section: fabricpool
    - title: Use StorageGRID
      url: "/landing-use/index.html"  
      entries:
      - section: tenant
      - section: s3
      - section: swift
    - title: Monitor and troubleshoot
      url: "/landing-monitor-troubleshoot/index.html"  
      entries:
      - section: monitor
      - section: troubleshoot
      - section: audit
    - title: Expand your grid
      entries:
      - section: expand
    - title: Maintain your grid
      entries:
      - title: Overview
        url: "/maintain/index.html"
      - title: Download Recovery Package
        url: "/maintain/downloading-recovery-package.html"
      - title: Decommission node or site
        url: "/maintain/decommission-procedure.html"
      - title: Rename gride, node, or site
        url: "/maintain/rename-grid-site-node-overview.html"
      - title: Maintain network
        url: "/maintain/updating-subnets-for-grid-network.html"
      - title: Host and middleware procedures
        url: "/maintain/linux-migrating-grid-node-to-new-host.html"
      - title: Grid node procedures
        url: "/maintain/grid-node-procedures.html"
    - title: Recover nodes 
      entries:
      - title: Overview
        url: "/maintain/grid-node-recovery-procedures.html"
      - title: Warnings and considerations for grid node recovery
        url: "/maintain/warnings-and-considerations-for-grid-node-recovery.html"
      - title: Select node recovery procedure
        url: "/maintain/selecting-node-recovery-procedure.html"
      - title: Recover from Storage Node failures
        entries:
        - title: Overview
          url: "/maintain/recovering-from-storage-node-failures.html"
        - title: Recover Storage Node down more than 15 days
          url: "/maintain/recovering-storage-node-that-has-been-down-more-than-15-days.html"
    - title: Enable StorageGRID
      url: /storagegrid-enable.html
    - title: Other versions
      url: /earlier-versions.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: StorageGRID documentation
  repo: storagegrid-family