settings:
  name: "StorageGRID 11.8"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: false
    harmony_enabled: false
sidebar:
  entries:
    - title: StorageGRID 11.8 Docs
      url: /index.html
    - title: Release notes
      url: "/release-notes/index.html"
    - title: Get started
      url: "/landing-get-started/index.html"  
      entries:
      - section: primer
      - section: network
      - title: Quick start
        url: /quick-start.html      
    - title: Install and upgrade
      url: "/landing-install-upgrade/index.html"  
      entries:
      - title: Install appliances
        url: /storagegrid-hardware.html 
      - section: rhel
      - section: ubuntu
      - section: vmware
      - section: upgrade
    - title: Configure and manage
      url: "/landing-configure-manage/index.html"  
      entries:
      - section: admin
      - section: ilm
      - section: harden
      - section: fabricpool
    - title: Use StorageGRID
      url: "/landing-use/index.html"  
      entries:
      - section: tenant
      - section: s3
      - section: swift
    - title: Monitor and troubleshoot
      url: "/landing-monitor-troubleshoot/index.html"  
      entries:
      - section: monitor
      - section: troubleshoot
      - section: audit
    - title: Maintain
      url: "/landing-maintain/index.html"    
      entries:
      - section: expand
      - section: maintain   
    - title: Enable StorageGRID
      url: /storagegrid-enable.html
    - title: Other versions
      url: /earlier-versions.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: StorageGRID documentation
  repo: storagegrid-family