---
permalink: upgrade/whats-new.html
sidebar: sidebar
keywords: what is new in StorageGRID 11.8
summary: 'This release of StorageGRID introduces the following features.'
---
= What's new in StorageGRID 11.8
:icons: font
:imagesdir: ../media/

[.lead]
This release of StorageGRID introduces the following features and functional changes.

== New features

=== Assign policy to ILM tags
Allows per-bucket ILM policies controlled with bucket tags. Multiple active and inactive ILM policies can exist at the same time.

=== Manage drives tab
New Manage drives tab (on the Nodes page) for SGF6112 appliance.

=== Configurable default consistency
You can change the link:../s3/consistency-controls.html[grid-wide default consistency] using the Grid Manager (*CONFIGURATION* > *Storage settings* > *Default bucket consistency*) or the grid-config endpoint of the link:../admin/using-grid-management-api.html[Grid Management private API]. The new default will be applied to buckets created after the change.

=== New tenant permission
The tenant permission, View all buckets, has been added. See link:../tenant/tenant-management-permissions.html[Tenant management permissions].

=== Temporary installation passwords
When you link:../vmware/deploying-storagegrid-node-as-virtual-machine.html[deploy a StorageGRID node as a virtual machine] or use VMware vSphere to link:../vmware/automating-grid-node-deployment-in-vmware-vsphere.html[automate grid node deployment], you are now prompted to set a temporary installation password. This password is used only if you need to access the VM console or use SSH before the new node joins the grid.

== Updates to existing features

=== S3 Console no longer experimental
Additional functionality described in link:../tenant/use-s3-console.html[Use S3 Console].

=== Rolling reboot procedure
You can use the link:../maintain/rolling-reboot-procedure.html[rolling reboot procedure] to reboot multiple grid nodes without causing a service disruption.

=== Management API stack trace
The *Management API stack trace* security setting lets you control whether a stack trace is returned in Grid Manager and Tenant Manager API error responses. See link:../admin/changing-browser-session-timeout-interface.html[Change interface security settings].

=== Archive Nodes can be decommissioned
You can now use the Decommission Nodes procedure to remove any unused Archive Nodes that are disconnected from the grid. See link:../maintain/decommissioning-disconnected-grid-nodes.html[Decommission disconnected grid nodes].

NOTE: Archive Nodes were deprecated in StorageGRID 11.7. 

=== SSO supports user principal names
When configuring single sign-on (SSO) for Active Directory Federation Service (AD FS) or PingFederate, you can now map the user principal name to `Name ID` in the claims rule or to `sAMAccountName=${username}` in the adapter instance.

=== Can use load balancer for management interface traffic
Create load balancer endpoints to manage the management interface workload on Admin Nodes. See link:../admin/managing-load-balancing.html[considerations for load balancing]. As part of this change, you can now use Grid Manager and Tenant Manager ports 443, 8443, and 9443 when creating HTTPS load balancer endpoints for S3 or Swift client access. 

=== TLS policy configuration and KMIP support
* StorageGRID now supports either the TLS 1.2 or TLS 1.3 protocol for KMIP connections. See link:../admin/kms-considerations-and-requirements.html[Considerations and requirements for using a key management server].

* Hashicorp is now fully supported for KMIP.

* Enhancements were made to TLS policy configuration. See link:../admin/manage-tls-ssh-policy.html[Manage the TLS and SSH policy].

=== Account clone improvement
Existing accounts can be cloned to a remote grid.

=== Automatic volume restoration
Added a toggle for volume restoration to occur automatically.

=== Changes to erasure coding configurations and rebalance procedure
Improvements to erasure coding configurations.

Erasure coding rebalance procedure is now considered complete when the new Site Imbalance metric reaches 0.02 or when the job has been running continuously for 30 days.

=== Metadata-only Storage Nodes
You can now specify that a new link:../primer/what-storage-node-is.html#types-of-storage-nodes[software-based Storage Node] will be used to store only metadata instead of both objects and metadata.

=== UEFI secure boot for appliances
Enabled on SGF6112 and SG6160. Significant performance improvements for SGF6112.

=== FIPS support
Support for FIPS 140-2 validated cryptography.

=== Kafka endpoints
Support for Kafka endpoints for bucket event notification.

=== Local key manager for DAS SED/FIPS VNMe SSDs
StorageGRID 11.8 and StorageGRID Appliance Installer firmware version 3.8.0 supports a local key manager for DAS NVMe SSD drive passwords.

=== S3 changes

* S3 delete markers with UUIDs.
* S3 Select ScanRange used when provided in requests for CSV and Parquet files.
* S3 REST API changes. See link:../s3/changes-to-s3-rest-api-support.html[Changes to S3 REST API support].

== User interface changes

=== Grid Manager integrated with BlueXP
See https://docs.netapp.com/us-en/bluexp-storagegrid/index.html[StorageGRID management using BlueXP^].

=== Information moved for additional ports on untrusted Client Network

The Grid Manager list of ports open to the untrusted Client Network is now located in a column named, "Open to untrusted Client network" at *CONFIGURATION* > *Network* > *Load balancer endpoints* > *Management interface* (previously located on the Firewall control page).

== Documentation changes

* The documentation for StorageGRID appliances was moved to a link:https://review.docs.netapp.com/us-en/storagegrid-appliances_main/[new documentation site].