---
permalink: tenant/manage-consistency-setting.html
sidebar: sidebar
keywords: how to manage bucket consistency, how to change bucket consistency, read after new write, read-after-new-write, strong site, strong-site, strong global, strong-global
summary: 'Consistency settings provide a balance between the availability of the objects and the consistency of those objects across different Storage Nodes and sites. You can change the consistency setting for operations performed on the objects in S3 buckets.'
---
= Manage a bucket's consistency setting
:icons: font
:imagesdir: ../media/

[.lead]
Consistency settings provide a balance between the availability of the objects and the consistency of those objects across different Storage Nodes and sites. You can change the consistency setting for operations performed on the objects in S3 buckets.

.Before you begin
* You are signed in to the Tenant Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You belong to a user group that has the link:tenant-management-permissions.html[Manage all buckets or Root access permission]. These permissions override the permissions settings in group or bucket policies.

== Consistency guidelines

In general, you should use the *Read-after-new-write* consistency setting for your buckets.

The following bucket configurations support strong consistency. These configurations require that more Storage Nodes are available for the configuration to be successful.

* <<change-bucket-consistency,Bucket consistency (change)>>
* Background empty bucket deletion
* link:configuring-cross-origin-resource-sharing-cors.html[CORS configuration]
* link:../ilm/create-ilm-rule-define-placements.html[Last Access Time configuration]
* Bucket lifecycle configuration
* Platform services configuration: Notification or Replication
* Bucket policy configuration
* Bucket tagging

== [[change-bucket-consistency]]Change a bucket's consistency setting

If the *Read-after-new-write* consistency setting does not meet the client application's requirements, you can change the consistency setting by setting the bucket consistency setting or by using the `Consistency-Control` header. The `Consistency-Control` header overrides the bucket consistency setting.

NOTE: When you change a bucket's consistency setting, only those objects that are ingested after the change are guaranteed to meet the revised setting.

.Steps

. Select *View buckets* from the dashboard, or select *STORAGE (S3)* > *Buckets*.
. Select the bucket name from the table.
+
The bucket details page appears.

. From the *Bucket options* tab, select the ** accordion.

. Select a consistency setting for operations performed on the objects in this bucket.
+
* *All*: Provides the highest level of consistency. All nodes receive the data immediately, or the request will fail.

* *Strong-global*: Guarantees read-after-write consistency for all client requests across all sites.

* *Strong-site*: Guarantees read-after-write consistency for all client requests within a site.

* *Read-after-new-write* (default): Provides read-after-write consistency for new objects and eventual consistency for object updates. Offers high availability and data protection guarantees. Recommended for most cases.

* *Available*: Provides eventual consistency for both new objects and object updates. For S3 buckets, use only as required (for example, for a bucket that contains log values that are rarely read, or for HEAD or GET operations on keys that don't exist). Not supported for S3 FabricPool buckets.

. Select *Save changes*.