---
permalink: tenant/manage-consistency-setting.html
sidebar: sidebar
keywords: how to manage bucket consistency, how to change bucket consistency, read after new write, read-after-new-write, strong site, strong-site, strong global, strong-global
summary: 'Consistency values can be used to specify the availability of bucket setting changes as well as to provide a balance between the availability of the objects within a bucket and the consistency of those objects across different Storage Nodes and sites. You can change the consistency values to be different from the default values so that client applications can meet their operational needs.'
---
= Manage a bucket's consistency setting
:icons: font
:imagesdir: ../media/

[.lead]
Consistency values can be used to specify the availability of bucket setting changes as well as to provide a balance between the availability of the objects within a bucket and the consistency of those objects across different Storage Nodes and sites. You can change the consistency values to be different from the default values so that client applications can meet their operational needs.

.Before you begin
* You are signed in to the Tenant Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You belong to a user group that has the link:tenant-management-permissions.html[Manage all buckets or Root access permission]. These permissions override the permissions settings in group or bucket policies.

== Bucket consistency setting guidelines

The bucket consistency setting is used to determine the consistency for client applications affecting objects within that S3 bucket. In general, you should use the *Read-after-new-write* consistency setting for your buckets.

== [[change-bucket-consistency]]Change a bucket's consistency setting

If the *Read-after-new-write* consistency does not meet the client application's requirements, you can change the consistency by setting the bucket consistency setting or by using the `Consistency-Control` header. The `Consistency-Control` header overrides the bucket consistency setting.

NOTE: When you change a bucket's consistency setting, only those objects that are ingested after the change are guaranteed to meet the revised setting.

.Steps

. Select *View buckets* from the dashboard, or select *STORAGE (S3)* > *Buckets*.
. Select the bucket name from the table.
+
The bucket details page appears.

. From the *Bucket options* tab, select the ** accordion.

. Select a consistency setting for operations performed on the objects in this bucket.
+
* *All*: Provides the highest level of consistency. All nodes receive the data immediately, or the request will fail.

* *Strong-global*: Guarantees read-after-write consistency for all client requests across all sites.

* *Strong-site*: Guarantees read-after-write consistency for all client requests within a site.

* *Read-after-new-write* (default): Provides read-after-write consistency for new objects and eventual consistency for object updates. Offers high availability and data protection guarantees. Recommended for most cases.

* *Available*: Provides eventual consistency for both new objects and object updates. For S3 buckets, use only as required (for example, for a bucket that contains log values that are rarely read, or for HEAD or GET operations on keys that don't exist). Not supported for S3 FabricPool buckets.

. Select *Save changes*.

== Change a bucket's consistency setting

Buckets have multiple settings that affect the behavior of the buckets and the objects within those buckets. 

The following bucket settings use *strong* consistency by default. Modifications to these settings might not be available when two or more Storage Nodes are not available within any site, or if a site is not available.

* link:use-s3-console.html[Background empty bucket deletion]
* link:../ilm/create-ilm-rule-define-placements.html[Last Access Time]
* link:../s3/create-s3-lifecycle-configuration.html[Bucket lifecycle]
* link:../s3/bucket-and-group-access-policies.html[Bucket policy]
* link:../admin/what-is-autosupport.html[Bucket tagging]
* link:changing-bucket-versioning.html[Bucket versioning]
* link:using-s3-object-lock.html[S3 Object Lock]

NOTE: The consistency value for bucket versioning, S3 Object Lock, and bucket encryption cannot be set to a value that is not strongly consistent.

The following bucket settings do not use strong consistency and have higher availability for changes. Changes to these settings might take some time before having an effect.

* link:what-platform-services-are.html[Platform services configuration: Notification, Replication, or Search integration]
* link:configuring-cross-origin-resource-sharing-cors.html[CORS configuration]
* <<change-bucket-consistency,Bucket consistency (change)>>

[[change-bucket-consistency]]To specify a different consistency value when changing a bucket setting:

* Use the Consistency-Control header on the s3 PUT interface for the bucket setting
* Use the reducedConsistency or force options on the mgmt-api `PUT/org/containers/{bucketName}/{bucketSetting}`