---
permalink: tenant/use-s3-console.html
sidebar: sidebar
keywords: how to use s3 console
summary: 'You can use S3 Console to view and manage the objects in an S3 bucket.'
---
= Use S3 Console
:icons: font
:imagesdir: ../media/

[.lead]
You can use S3 Console to view and manage the objects in an S3 bucket.

S3 Console allows you to:

*	Upload, download, rename, copy, move, and delete objects
*	View, revert, download, and delete object versions
* Search for objects by prefix
* Manage object tags
* View object metadata
*	View, create, rename, copy, move, and delete folders

NOTE: Tenants should only use S3 Console when performing functions for a small number of objects, such as when uploading objects to simulate a new ILM policy, troubleshooting ingest issues, or using proof-of-concept or non-production grids.

.Before you begin

* You are signed in to the Tenant Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* If you want to view objects, buckets, and bucket configuration, you belong to a user group that has the View all buckets link:tenant-management-permissions.html[permission].
* If you want to manage objects, buckets, and bucket configuration, you belong to a user group that has the Root access permission or that has both the Manage all buckets and Use S3 Console tab link:tenant-management-permissions.html[permissions].
* You have created a bucket.
* An S3 Group or Bucket policy has been configured for the user.
* You know the user's access key ID and secret access key. Optionally, you have a `.csv` file containing this information. See the link:creating-your-own-s3-access-keys.html[instructions for creating access keys].

.Steps

. Select *STORAGE* > *Buckets* > *_bucket name_*.
. Select the S3 Console tab.
. Paste the access key ID and secret access key into the fields. Otherwise, select *Upload access keys* and select your `.csv` file.
. Select *Sign in*.
. The table of bucket objects appears. You can manage objects as needed.

.Results

Note the following outcomes:

Operations on folders:: When you move, copy, or rename a folder, all objects in the folder are updated one at a time, which might take time.

Bucket versioning disabled:: When you overwrite or delete an object in a bucket with versioning disabled, the operation is permanent. See link:changing-bucket-versioning.html[Change object versioning for a bucket].