---
permalink: rhel/index.html
sidebar: sidebar
keywords: red hat enterprise linux, rhel, centos linux
summary: 'Installing a StorageGRID system in a Red Hat Enterprise Linux (RHEL) or CentOS Linux environment includes three primary steps.'
---
= Install Red Hat Enterprise Linux or CentOS: Overview
:icons: font
:imagesdir: ../media/

[.lead]
Installing a StorageGRID system in a Red Hat Enterprise Linux (RHEL) or CentOS Linux environment includes three primary steps.

. *Preparation*
 ** Learn about link:cpu-and-ram-requirements.html[CPU and RAM requirements].
 ** Learn about link:storage-and-performance-requirements.html[hardware and storage requirements].
 ** Learn about the specifics of link:../network/index.html[StorageGRID networking].
 ** link:how-host-wide-settings-change.html[Prepare the Linux servers] that will host your StorageGRID nodes.

. *Deployment*
+
Deploy grid nodes using the appropriate user interface. +
When you deploy grid nodes, they are created as part of the StorageGRID system and connected to one or more networks.

* To deploy software-based grid nodes on the hosts you prepared in step 1, use the Linux command line and link:creating-node-configuration-files.html[node configuration files].

* To deploy StorageGRID appliance nodes, follow the https://review.docs.netapp.com/us-en/storagegrid-appliances_main/installconfig/index.html[Quick start for hardware installation^].

. *Configuration*
+
When all nodes have been deployed, use the Grid Manager to link:navigating-to-grid-manager.html[configure the grid and complete the installation].

. *Alternative approaches*
+
Instead of following the standard approach for deploying and configuring a StorageGRID system, you can use these alternative approaches:

* For these options, see link:automating-installation.html[Automate the installation]
** Use a standard orchestration framework such as Ansible, Puppet, or Chef to install RHEL or CentOS, configure networking and storage, install the container engine and the StorageGRID host service, and deploy virtual grid nodes.
** Automate the deployment and configuration of the StorageGRID system using a Python configuration script (provided in the installation archive).
** Automate the deployment and configuration of appliance grid nodes with a Python configuration script (available from the installation archive or from the StorageGRID Appliance Installer).

* For this option, see link:overview-of-installation-rest-api.html[Overview of installation REST API]
** If you are an advanced developer of StorageGRID deployments, use the installation REST APIs to automate the installation of StorageGRID grid nodes.