---
permalink: admin/what-is-autosupport.html
sidebar: sidebar
keywords: autosupport, technical support, storagegrid health, system status, Active IQ
summary: 'The AutoSupport feature enables your StorageGRID system to send health and status messages to technical support.'
---
= Use AutoSupport: Overview
:icons: font
:imagesdir: ../media/

[.lead]
The AutoSupport feature enables your StorageGRID system to send health and status messages to technical support. 

Using AutoSupport can significantly speed problem determination and resolution. Technical support can also monitor the storage needs of your system and help you determine if you need to add new nodes or sites. Optionally, you can configure AutoSupport messages to be sent to one additional destination.

You should configure StorageGRID AutoSupport only on the primary Admin Node. However, you must configure <<hardware_autosupport,hardware AutoSupport>> on each appliance.

== Information included in AutoSupport messages

AutoSupport messages include information such as the following:

* StorageGRID software version
* Operating system version
* System-level and location-level attribute information
* Recent alerts and alarms (legacy system)
* Current status of all grid tasks, including historical data
* Admin Node database usage
* Number of lost or missing objects
* Grid configuration settings
* NMS entities
* Active ILM policy
* Provisioned grid specification file
* Diagnostic metrics

You can enable the AutoSupport feature and the individual AutoSupport options when you first install StorageGRID, or you can enable them later. If AutoSupport is not enabled, a message appears on the Grid Manager dashboard. The message includes a link to the AutoSupport configuration page.

NOTE: If you close the message, it will not appear again until your browser cache is cleared, even if AutoSupport remains disabled.

.AutoSupport package content
[%collapsible]
====
[cols="2a,2a,3a" options="header"]
|===
| File name| Fields| Description

| AUTOSUPPORT-HISTORY.XML
| AutoSupport Sequence Number

Destination for this AutoSupport

Trigger Event

Status of Delivery

Delivery Attempts

AutoSupport Subject

Delivery URI

Last error

AutoSupport PUT Filename

Time of Generation

Autosupport Compressed Size

Autosupport Decompressed Size

Total Collection Time (ms)
| AutoSupport history file

| AUTOSUPPORT.XML
| Node

Protocol to contact support

Support URL for HTTP/HTTPS

Support Address

AutoSupport OnDemand State

AutoSupport OnDemand Server URL

AutoSupport OnDemand Polling Interval
| AutoSupport status file. Provides details of protocol used, technical support URL and address, polling interval, and OnDemand AutoSupport if enabled or disabled.

| BUCKETS.XML
| Bucket ID

Account ID

Build Version

Location Constraint Configuration

Compliance Enabled

Compliance Configuration

S3 Object Lock Enabled

S3 Object Lock Configuration

Consistency Configuration

CORS Enabled

CORS Configuration

Last Access Time Enabled

Policy Enabled

Policy Configuration

Notifications Enabled

Notifications Configuration

Cloud Mirror Enabled

Cloud Mirror Configuration

Search Enabled

Search Configuration

Swift Read ACL Enabled

Swift Read ACL Configuration

Swift Write ACL Enabled

Swift Write ACL Configuration

Bucket Tagging Enabled

Bucket Tagging Configuration

Versioning Configuration
| Provides configuration details and statistics at the bucket level. Example of bucket configurations include platform services, compliance, and bucket consistency level.

| GRID-CONFIGURATIONS.XML
| Attribute ID

Attribute Name

Value

Index

Table ID

Table Name
| Grid-wide configuration information file. Contains information about grid certificates, metadata reserved space, grid-wide configuration settings (compliance, S3 Object Lock, object compression, alerts, syslog, and ILM configuration), EC profile details, DNS name, NMS name, and more.

| GRID-SPEC.XML
| Grid specifications, raw XML
| Used for configuring and deploying StorageGRID. Contains grid specifications, NTP server IP, DNS server IP, network topology, and hardware profiles of the nodes.

| GRID-TASKS.XML
| Node

Service Path

Attribute ID

Attribute name

Value

Index

Table ID

Table name
| Grid tasks (maintenance procedures) status file. Provides details of the grid's active, aborted, completed, failed, and pending tasks.

| ILM-STATUS.XML
| Node

Service path

Attribute ID

Attribute name

Value

Index

Table ID

Table name
| ILM metrics information file. Contains ILM evaluation rates for each node and grid-wide metrics.

| ILM.XML
| ILM raw XML
| ILM active policy file. Contains details about the active ILM policy, such as storage pool ID, ingest behavior, filters, rules, and description.

| LOG.TGZ
| _n/a_
| Downloadable log file. Contains `bycast-err.log` and `servermanager.log` from each node.

| MANIFEST.XML
| Collection order

AutoSupport content filename for this data

Description of this data item

Number of bytes collected

Time spent collecting

Status of this data item

Description of the error

AutoSupport content type for this data
| Contains AutoSupport metadata and brief descriptions of all AutoSupport XML files.

| NMS-ENTITIES.XML
| Attribute index

Entity OID

Node ID

Device model ID

Device model version

Entity name
| Group and service entities in the NMS tree. Provides grid topology details. The node can be determined based on the services running on the node.

| OBJECTS-STATUS.XML
| Node

Service path

Attribute ID

Attribute name

Value

Index

Table ID

Table name
| Object status, including background scan status, active transfer, transfer rate, total transfers, delete rate, corrupted fragments, lost objects, missing objects, repair attempted, scan rate, estimated scan period, repair completion status, and more.

| SERVER-STATUS.XML
| Node

Service path

Attribute ID

Attribute name

Value

Index

Table ID

Table name
| Server configurations and events file. Contains these details for each node: platform type, operating system, installed memory, available memory, storage connectivity, storage appliance chassis serial number, storage controller failed drive count, compute controller chassis temperature, compute hardware, compute controller serial number, power supply, drive size, drive type, and more.

| SERVICE-STATUS.XML
| Node

Service path

Attribute ID

Attribute name

Value

Index

Table ID

Table name
| Service node information file. Contains details such as allocated table space, free table space, reaper metrics of the database, segment repair duration, repair job duration, auto job restarts, auto job aborts, and more.

| STORAGE-GRADES.XML
| Storage grade ID

Storage grade name

Storage node ID

Storage node path
| Storage grade definitions file for each Storage Node.

| SUMMARY-ATTRIBUTES.XML
| Group OID

Group Path

Summary attribute ID

Summary attribute name

Value

Index

Table ID

Table name
| High-level system status data that summarizes StorageGRID usage information. Provides details such as name of grid, names of sites, number of Storage Nodes per grid and per site, license type, license capacity and usage, software support terms, and details of S3 and Swift operations.

| SYSTEM-ALARMS.XML
| Node

Service path

Severity

Alarmed attribute

Attribute name

Status

Value

Trigger time

Acknowledge time
| System level alarms (deprecated) and status data used to indicate abnormal activities or potential problems.

| SYSTEM-ALERTS.XML
| Name

Severity

Node name

Alert Status

Site name

Alert triggered time

Alert resolved time

Rule ID

Node ID

Site ID

Silenced

Other annotations

Other labels
| Current system alerts that indicate potential problems in the StorageGRID system.

| USERAGENTS.XML
| User agent

Number of days

Total HTTP requests

Total bytes ingested

Total bytes retrieved

PUT requests

GET requests

DELETE requests

HEAD requests

POST requests

OPTIONS requests

Average request time (ms)

Average PUT request time (ms)

Average GET request time (ms)

Average DELETE request time (ms)

Average HEAD request time (ms)

Average POST request time (ms)

Average OPTIONS request time (ms)
| Statistics based on the application user agents. For example, the number of PUT/GET/DELETE/HEAD operations per user agent and total bytes size of each operation.

| X-HEADER-DATA
| X-Netapp-asup-generated-on

X-Netapp-asup-hostname

X-Netapp-asup-os-version

X-Netapp-asup-serial-num

X-Netapp-asup-subject

X-Netapp-asup-system-id

X-Netapp-asup-model-name
| AutoSupport header data.
|===
====

== What is Active IQ?

include::../_include/autosupport-activeiq.adoc[]

== Protocols for sending AutoSupport messages

You can choose one of three protocols for sending AutoSupport messages:

* HTTPS
* HTTP
* SMTP

If you use SMTP as the protocol for AutoSupport messages, you must configure an SMTP mail server.

== AutoSupport options

You can use any combination of the following options to send AutoSupport messages to technical support:

* *Weekly*: Automatically send AutoSupport messages once per week. Default setting: Enabled.
* *Event-triggered*: Automatically send AutoSupport messages every hour or when significant system events occur. Default setting: Enabled.
* *On Demand*: Allow technical support to request that your StorageGRID system send AutoSupport messages automatically, which is useful when they are actively working an issue (requires HTTPS AutoSupport transmission protocol). Default setting: Disabled.
* *User-triggered*: Manually send AutoSupport messages at any time.

== [[hardware_autosupport]] AutoSupport for appliances

AutoSupport for appliances reports StorageGRID hardware issues, while StorageGRID AutoSupport reports StorageGRID software issues (except for the SGF6112, where StorageGRID AutoSupport reports both hardware and software issues). You must configure AutoSupport on each appliance, except for the SGF6112 which does not require additional configuration. AutoSupport is implemented differently for services and storage appliances.

You must enable AutoSupport in SANtricity for each storage appliance. You can configure SANtricity AutoSupport during initial appliance setup or after an appliance has been installed:

* For SG6000 and SG5700 appliances, https://review.docs.netapp.com/us-en/storagegrid-appliances_main/installconfig/accessing-and-configuring-santricity-system-manager.html[configure AutoSupport in SANtricity System Manager^]

AutoSupport messages from E-Series appliances can be included in StorageGRID AutoSupport if you configure AutoSupport delivery by proxy in link:../admin/sending-eseries-autosupport-messages-through-storagegrid.html[SANtricity System Manager].

StorageGRID AutoSupport does not report hardware issues, such as DIMM or host interface card (HIC) faults. However, some component failures might trigger link:../monitor/alerts-reference.html[hardware alerts]. For StorageGRID appliances with a baseboard management controller (BMC), such as the SG100, SG1000, SG6060, or SGF6024, you can configure email and SNMP traps to report hardware failures:

* https://review.docs.netapp.com/us-en/storagegrid-appliances_main/installconfig/setting-up-email-notifications-for-alerts.html[Set up email notifications for alerts^]
* https://review.docs.netapp.com/us-en/storagegrid-appliances_main/installconfig/configuring-snmp-settings-for-bmc.html[Configure SNMP settings^] for the SG6000-CN controller or the SG100 and SG1000 services appliances

.Related information

https://mysupport.netapp.com/site/global/dashboard[NetApp Support^]