---
permalink: s3/s3-operations-tracked-in-audit-logs.html
sidebar: sidebar
keywords: audit log, auditing bucket and object operations, S3 audit messages 
summary: 'Audit messages are generated by StorageGRID services and stored in text log files. You can review the S3-specific audit messages in the audit log to get details about bucket and object operations.'
---
= S3 operations tracked in the audit logs
:icons: font
:imagesdir: ../media/

[.lead]
Audit messages are generated by StorageGRID services and stored in text log files. You can review the S3-specific audit messages in the audit log to get details about bucket and object operations.

Go to link:../audit/accessing-audit-log-file.html[Access audit log file] to learn how to access the audit log. Go to link:../audit/audit-messages-main.html[Audit messages] to learn about the specific messages used for S3 client write and read operations.


== Bucket operations tracked in the audit logs

* CreateBucket
* DeleteBucket
* DeleteBucketTagging
* DeleteObjects
* GetBucketTagging
* HeadBucket
* ListObjects
* ListObjectVersions
* PUT Bucket compliance
* PutBucketTagging
* PutBucketVersioning

== Object operations tracked in the audit logs

* CompleteMultipartUpload
* CopyObject
* DeleteObject
* GetObject
* HeadObject
* PutObject
* RestoreObject
* SelectObject
* UploadPart (when an ILM rule uses Balanced or Strict ingest)
* UploadPartCopy (when an ILM rule uses Balanced or Strict ingest)

