---
permalink: monitor/viewing-manage-drives-tab.html
sidebar: sidebar
keywords: Manage drives tab, hardware diagnostics, fail drive, logically replace drive
summary: 'The Manage drives tab on the Nodes page in Grid Manager enables you to access details and perform actions on SG6100 series appliance drives.'
---
= View the Manage drives tab (SG6100 series only)
:icons: font
:imagesdir: ../media/

[.lead]
The Manage drives tab on the Nodes page in Grid Manager enables you to access details and perform actions on SG6100 series appliance drives.

NOTE: The Manage drives tab is shown only for SG6100 series storage appliance nodes.

Using the Manage drives tab, you can do the following:

* View a layout of the data storage drives in the appliance.
* View a table that lists each drive location, type, status, firmware version, and serial number.
* Perform monitoring and maintenance functions on each drive.

To perform maintenance functions on the Manage drives tab, you must have the link:../admin/admin-group-permissions.html[Storage appliance administrator or Root access permission].

For information about using the functions on the Manage drives tab, see https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/manage-drives-tab.html[Use the Manage drives tab^].