---
permalink: maintain/considerations-for-decommissioning-grid-nodes.html
sidebar: sidebar
keywords: storagegrid, decommission
summary: 'Before you start this procedure to decommission one or more nodes, understand the implications of removing each type of node. Upon the successful decommissioning of a node, its services will be disabled and the node will be automatically shut down.'
---
= General considerations for grid node decommission
:icons: font
:imagesdir: ../media/

[.lead]
Before you start this procedure to decommission one or more nodes, understand the implications of removing each type of node. Upon the successful decommissioning of a node, its services will be disabled and the node will be automatically shut down.

You can't decommission a node if doing so will leave StorageGRID in an invalid state. The following rules are enforced:

* You can't decommission the primary Admin Node.
* You can't decommission Archive Nodes.
* You can't decommission an Admin Node or a Gateway Node if one of its network interfaces is part of a high availability (HA) group. 
* You can't decommission a Storage Node if its removal would affect the ADC quorum.
* You can't decommission a Storage Node if it is required for the active ILM policy.
* You should not decommission more than 10 Storage Nodes in a single Decommission Node procedure.
* You can't decommission a connected node if your grid includes any disconnected nodes (nodes whose health is Unknown or Administratively Down). You must decommission or recover the disconnected nodes first.
* If your grid contains multiple disconnected nodes, the software requires you to decommission them all at the same time, which increases the potential for unexpected results.
* If a disconnected node can't be removed (for example, a Storage Node that is required for the ADC quorum), no other disconnected node can be removed.

IMPORTANT: Don't remove a grid node's virtual machine or other resources until instructed to do so in decommission procedures.

[cols="2a,1a,3a" options="header"]
|===
| Node type| Can decommission?| Rules and guidelines

| Primary Admin Node
| No
|

|Archive node
| No
|

| Admin or Gateway Node
| No
| Can't decommission if one of the node's network interfaces is part of a high availability (HA) group

| Storage Node
| No
| Can't decommission if the node's removal would affect the ADC quorum

| Storage Node
| No
| Can't decommission if the node is required for the active ILM policy

| 10 Storage Nodes
| Yes, maximum number allowed
| This is the maximum number of Storage Nodes for a single Decommission Node procedure.

| Any connected node 
| Possibly
| Can't decommission if your grid includes any disconnected nodes (nodes whose health is Unknown or Administratively Down). Decommission or recover the disconnected nodes first.

| Multiple disconnected nodes
| Possibly
| You must decommission them all at the same time, which increases the potential for unexpected results.

*Note*: If a disconnected node can't be removed (for example, a Storage Node that is required for the ADC quorum), no other disconnected node can be removed.
|===