---
permalink: maintain/step-3-revise-ilm-policy.html
sidebar: sidebar
keywords: storagegrid, recover, revise ilm policies
summary: 'From Step 3 \(Revise ILM Policies\) of the Decommission Site wizard, you can determine if the site is referred to by any ILM policy.'
---
= Step 3: Revise ILM Policies
:icons: font
:imagesdir: ../media/

[.lead]
From Step 3 (Revise ILM Policies) of the Decommission Site wizard, you can determine if the site is referred to by any ILM policy.

.Before you begin

You have a good understanding of how to link:../ilm/index.html[manage objects with ILM]. You are familiar with creating storage pools and ILM rules and with simulating and activating an ILM policy.

.About this task

StorageGRID can't decommission a site if any ILM rule in any policy (active or inactive) references that site.

If an ILM policy refers to the site you want to remove, you must either:

* Edit each inactive policy so that it:

** Fully protects all object data.
** Doesn't refer to the site you're decommissioning.
** Doesn't use a storage pool that refers to the site or uses the All Sites option.
** Doesn't use an erasure-coding profile that refers to the site.
** Doesn't use the Make 2 Copies rule from StorageGRID 11.6 or earlier installations.

* Remove each active policy and create new policies that don't refer to the site you're decommissioning. Before you remove an active policy, you can clone it to more easily create a new policy.

CAUTION: Never create a single-copy ILM rule to accommodate the removal of a site. An ILM rule that creates only one replicated copy for any time period puts data at risk of permanent loss. If only one replicated copy of an object exists, that object is lost if a Storage Node fails or has a significant error. You also temporarily lose access to the object during maintenance procedures such as upgrades.

TIP: If you're performing a _connected site decommission_, you must consider how StorageGRID should manage the object data currently at the site you want to remove. Depending on your data protection requirements, the new rules can move existing object data to different sites or they can delete any extra object copies that are no longer needed.

Contact technical support if you need assistance designing a new policy.

.Steps

. From Step 3 (Revise ILM Policies), determine if any ILM policies refer to the site you selected to remove.

. If no policies are listed, select *Next* to go to link:step-4-remove-ilm-references.html[Step 4: Remove ILM References].

. If one or more ILM policies are listed in the table, decide if you want to remove the policy or edit the policy so it no longer references the site being decommissioned.

. For each _inactive_ policy:
.. Select the link for the policy in the Policy Name column.
+
The ILM policy details page for the policy appears in a new browser tab. The Decommission Site page will remain open on the other tab.

.. Remove or edit the policy:
+
* link:../ilm/working-with-ilm-rules-and-ilm-policies.html#remove-ilm-policy[Follow the instructions to remove a policy].
* link:../ilm/working-with-ilm-rules-and-ilm-policies.html#edit-ilm-policy[Follow the instructions to edit a policy].

.. Repeat these steps for each policy in the list.

. For each _inactive_ policy:
.. Select the link for the policy in the Policy Name column.
+
The ILM policy details page for the policy appears in a new browser tab. The Decommission Site page will remain open on the other tab.
.. Remove or edit the policy:
+
* link:../ilm/working-with-ilm-rules-and-ilm-policies.html#remove-ilm-policy[Follow the instructions to remove a policy].
* link:../ilm/working-with-ilm-rules-and-ilm-policies.html#edit-ilm-policy[Follow the instructions to edit a policy].
.. Repeat these steps for each active policy in the list.

. For each _active_ policy:
.. Select *ILM* > *Policies* and create a new policy that uses the new rules.
.. Select the active policy, and select *Clone*.
.. Specify a policy name and a reason for change.
.. Select rules for the cloned policy.
*** Clear all rules listed for Step 3 (Revise ILM Policies) of the Decommission Site page.
*** Select a default rule that does not refer to the site, then select *Continue*.
+
NOTE: Don't select the *Make 2 Copies* rule because that rule uses the *All Storage Nodes* storage pool, which is not allowed.

*** Select the other replacement rules you created. These rules should not refer to the site. As needed, link:../ilm/working-with-ilm-rules-and-ilm-policies.html[edit or replace the rules] that refer to the site.

.. After you select the other replacement rules, click *Select*.
.. Drag the rows to reorder the rules in the policy.
+
You can't move the default rule.
+
CAUTION: You must confirm that the ILM rules are in the correct order. When the policy is activated, new and existing objects are evaluated by the rules in the order listed, starting at the top.

.. Save the policy.

. Ingest test objects, and simulate the policy to ensure that the correct rules are applied.
+
CAUTION: Errors in an ILM policy can cause unrecoverable data loss. Carefully review and simulate the policy before activating it to confirm that it will work as intended.
+
CAUTION: When you activate a new ILM policy, StorageGRID uses it to manage all objects, including existing objects and newly ingested objects. Before activating a new ILM policy, review any changes to the placement of existing replicated and erasure-coded objects. Changing an existing object's location might result in temporary resource issues when the new placements are evaluated and implemented.

. Activate the new policy.
+
If you are performing a connected site decommission, StorageGRID begins to remove object data from the selected site as soon as you activate the new ILM policy. Moving or deleting all object copies might take weeks. Although you can safely start a site decommission while object data still exists at the site, the decommission procedure will complete more quickly and with fewer disruptions and performance impacts if you allow data to be moved from the site before starting the actual decommission procedure (by selecting *Start Decommission* in Step 5 of the wizard).

. Deactivate and delete any old policies that refer to the site being decommissioned.
+
NOTE: You can't decommission a site if any policy (active or inactive) refers to the site being decommissioned.

. Return to *Step 3 (Revise ILM Policies)* to ensure that no ILM rules in the new active policy refer to the site and the *Next* button is enabled.
+
NOTE: If any rules are listed, you must create and activate a new ILM policy before you can continue.

. If no rules are listed, select *Next*.
+
Step 4 (Remove ILM References) appears.


.Do we need these steps?

If necessary, select *ILM* > *Storage pools* to create one or more storage pools that don't refer to the site.

If you plan to use erasure coding, select *ILM* > *Erasure coding* to create one or more erasure-coding profiles.

You must select storage pools that don't refer to the site.

NOTE: Don't use the *All Storage Nodes* storage pool (StorageGRID 11.6 and earlier) in the erasure-coding profiles.