---
permalink: maintain/step-3-revise-ilm-policy.html
sidebar: sidebar
keywords: storagegrid, recover, revise ilm policies
summary: 'From Step 3 \(Revise ILM Policies\) of the Decommission Site wizard, you can determine if the site is referred to by any ILM policy.'
---
= Step 3: Revise ILM Policies
:icons: font
:imagesdir: ../media/

[.lead]
From Step 3 (Revise ILM Policies) of the Decommission Site wizard, you can determine if the site is referred to by any ILM policy.

.Before you begin

You have a good understanding of how to link:../ilm/index.html[manage objects with ILM]. You are familiar with creating storage pools and ILM rules and with simulating and activating an ILM policy.

.About this task

StorageGRID can't decommission a site if any ILM rule in any policy (active or inactive) references that site.

If an ILM policy refers to the site you want to decommission, use these options for removing references to the site:

* *Inactive policy*: Edit the policy to remove references to the site you want to decommission, or replace it with a new policy that doesn't reference the site.
* *Active policy*: Remove the policy, then create a new policy that doesn't reference the site you want to decommission. Before removing the policy, you can clone it to more easily create a new policy.

Ensure that all remaining policies meet these requirements:

** Fully protect all object data.
** Don't refer to the site you're decommissioning.
** Don't use storage pools that refer to the site or use the All Sites option.
** Don't use erasure-coding profiles that refer to the site.
** Don't use the Make 2 Copies rule from StorageGRID 11.6 or earlier installations.

CAUTION: Never create a single-copy ILM rule to accommodate the removal of a site. An ILM rule that creates only one replicated copy for any time period puts data at risk of permanent loss. If only one replicated copy of an object exists, that object is lost if a Storage Node fails or has a significant error. You also temporarily lose access to the object during maintenance procedures such as upgrades.

TIP: If you're performing a _connected site decommission_, you must consider how StorageGRID should manage the object data currently at the site you want to remove. Depending on your data protection requirements, new rules can move existing object data to different sites or they can delete any extra object copies that are no longer needed.

Contact technical support if you need assistance designing a new policy.

.Steps

. From Step 3 (Revise ILM Policies), determine if any ILM policies refer to the site you selected to decommission.

. If no policies are listed, select *Next* to go to link:step-4-remove-ilm-references.html[Step 4: Remove ILM References].

. If one or more ILM policies are listed, decide if you need to edit the policy, so it no longer references the site being decommissioned, or remove the policy.

.. Select the link for the policy in the Policy Name column.
+
The ILM policy details page for the policy appears in a new browser tab. The Decommission Site page will remain open on the other tab.

.. To edit the policy, link:../ilm/working-with-ilm-rules-and-ilm-policies.html#edit-ilm-policy[follow the steps to edit a policy]. Create or select storage pools that don't refer to the site.

.. To remove an active policy, first clone it by selecting *Clone*. Then link:../ilm/creating-ilm-policy.html[follow the steps for creating an ILM policy]. Also follow these guidelines:

*** Clear all rules listed for Step 3 (Revise ILM Policies) of the Decommission Site page.
*** Create and select a default rule and other rules that don't refer to the site. See link:../ilm/creating-default-ilm-rule.html[Create default ILM rule] and link:../ilm/what-ilm-rule-is.html[Create ILM rule].
*** link:../ilm/working-with-ilm-rules-and-ilm-policies.html[Edit or replace rules] that refer to the site.
*** link:../ilm/creating-storage-pool.html[Create one or more storage pools] that don't refer to the site.
+
NOTE: Don't select the *Make 2 Copies* rule because that rule uses the *All Storage Nodes* storage pool, which is not allowed.
+
CAUTION: You must confirm that the ILM rules are in the correct order. When the policy is activated, new and existing objects are evaluated by the rules in the order listed, starting at the top.

. Ingest test objects and simulate the policy to ensure that the correct rules are applied.
+
CAUTION: Errors in an ILM policy can cause unrecoverable data loss. Carefully review and simulate the policy before activating it to confirm that it will work as intended.

+
CAUTION: When you activate a new ILM policy, StorageGRID uses it to manage all objects, including existing objects and newly ingested objects. Before activating a new ILM policy, review any changes to the placement of existing replicated and erasure-coded objects. Changing an existing object's location might result in temporary resource issues when the new placements are evaluated and implemented.

. Activate the new policy.
+
If you are performing a connected site decommission, StorageGRID begins to remove object data from the selected site as soon as you activate the new ILM policy. Moving or deleting all object copies might take weeks. Although you can safely start a site decommission while object data still exists at the site, the decommission procedure will complete more quickly and with fewer disruptions and performance impacts if you allow data to be moved from the site before starting the actual decommission procedure (by selecting *Start Decommission* in Step 5 of the wizard).

. For each policy you want to remove:
.. Select the link for the policy in the Policy Name column.
+
The ILM policy details page for the policy appears in a new browser tab. The Decommission Site page will remain open on the other tab.
.. link:../ilm/working-with-ilm-rules-and-ilm-policies.html#remove-ilm-policy[Follow the steps to remove a policy].

. When you're finished making changes to ILM rules and policies, select *Next*.
+
Step 4 (Remove ILM References) appears.