---
permalink: primer/what-admin-node-is.html
sidebar: sidebar
keywords: admin nodes
summary: 'Admin Nodes provide management services such as system configuration, monitoring, and logging. Each grid must have one primary Admin Node and might have any number of non-primary Admin Nodes for redundancy.'
---
= What is an Admin Node?
:icons: font
:imagesdir: ../media/

[.lead]
Admin Nodes provide management services such as system configuration, monitoring, and logging. Each grid must have one primary Admin Node and might have any number of non-primary Admin Nodes for redundancy.

When you sign in to the Grid Manager or the Tenant Manager, you are connecting to an Admin Node. You can connect to any Admin Node, and each Admin Node displays a similar view of the StorageGRID system. However, maintenance procedures must be performed using the primary Admin Node.

Admin Nodes can also be used to load balance S3 and Swift client traffic.

== What is the preferred sender 

If your StorageGRID deployment includes multiple Admin Nodes, the primary Admin Node is the preferred sender for alert notifications, AutoSupport messages, SNMP traps and informs, and legacy alarm notifications. 

Under normal system operations, only the preferred sender sends notifications. However, all other Admin Nodes monitor the preferred sender. If a problem is detected, other Admin Nodes act as _standby senders_.

Multiple notifications might sent in these cases:

* If Admin Nodes become "islanded" from each other, both the preferred sender and the standby senders will attempt to send notifications, and multiple copies of notifications might be received.

* If standby sender detects problems with the preferred sender and starts sending notifications, the preferred sender might regain its ability to send notifications. If this occurs, duplicate notifications might be sent. The standby sender will stop sending notifications when it no longer detects errors on the preferred sender.
+
NOTE: When you test AutoSupport messages, all Admin Nodes send the test email. When you test alert notifications, you must sign in to every Admin Node to verify connectivity.

== Primary services for Admin Nodes

The following table shows the primary services for Admin Nodes; however, this table does not list all node services.

[cols="1a,2a" options="header"]
|===
| Service| Key function

| Audit Management System (AMS)
| Tracks system activity and events.

| Configuration Management Node (CMN)
| Manages system-wide configuration. Primary Admin Node only.

| Management Application Program Interface (mgmt-api)
| Processes requests from the Grid Management API and the Tenant Management API. 

| High Availability
| Manages high availability virtual IP addresses for groups of Admin Nodes and Gateway Nodes.

*Note:* This service is also found on Gateway Nodes.

| Load Balancer
| Provides load balancing of S3 and Swift traffic from clients to Storage Nodes.

*Note:* This service is also found on Gateway Nodes.

| Network Management System (NMS)
| Provides functionality for the Grid Manager.

| Prometheus
| Collects and stores time-series metrics from the services on all nodes.

| Server Status Monitor (SSM)
| Monitors the operating system and underlying hardware.
|===







