---
permalink: expand/index.html
sidebar: sidebar
keywords: expand grid
summary: 'You can expand the capacity or capabilities of your StorageGRID system without interrupting system operations.'
---
= Expand a grid: Overview
:icons: font
:imagesdir: ../media/

[.lead]
You can expand the capacity or capabilities of your StorageGRID system without interrupting system operations.

A StorageGRID expansion allows you to add:

* Storage volumes to Storage Nodes
* New grid nodes to an existing site
* An entire new site

The reason you are performing the expansion determines how many new nodes of each type you must add and the location of those new nodes. For example, there are different node requirements if you are performing an expansion to increase storage capacity, add metadata capacity, or add redundancy or new capabilities. 

Follow the steps for the type of expansion you're performing:

[cols="1a,1a,2a,2a" options="header"]
|===
| Step| Add storage volumes| Add grid nodes| Add a new site

| 1
| link:adding-storage-volumes-to-storage-nodes.html[Add storage volumes to Storage Nodes] (No additional steps required)
| link:adding-grid-nodes-to-existing-site-or-adding-new-site.html[Add grid nodes to existing site]
| link:adding-grid-nodes-to-existing-site-or-adding-new-site.html[Add new site]

| 2
|
2+| link:updating-subnets-for-grid-network.html[Update subnets]

| 3
|
2+| Deploy grid nodes for: link:deploying-new-grid-nodes.html#appliances-deploying-storage-gateway-or-non-primary-admin-nodes[Appliances], link:deploying-new-grid-nodes.html#vmware-deploy-grid-nodes[VMware], or link:deploying-new-grid-nodes.html#linux-deploy-grid-nodes[Linux]

*Note*: "Linux" refers to a Red Hat Enterprise Linux, Ubuntu, CentOS, or Debian deployment. Use the https://imt.netapp.com/matrix/#welcome[NetApp Interoperability Matrix Tool (IMT)^] to get a list of supported versions.

| 4
|
2+| link:performing-expansion.html[Perform the expansion]

| 5
|
2+| link:configuring-expanded-storagegrid-system.html[Configure the expanded system]
|===