---
permalink: ilm/activating-ilm-policy.html
sidebar: sidebar
keywords: activate ilm policy, information lifecycle policy
summary: 'After you add ILM rules to a policy, simulate the policy, and confirm it behaves as you expect, you are ready to activate the policy.'
---
= Activate the ILM policy
:icons: font
:imagesdir: ../media/

[.lead]
After you add ILM rules to a policy, simulate the policy, and confirm it behaves as you expect, you are ready to activate the policy.

.Before you begin

* You are signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You have link:../admin/admin-group-permissions.html[specific access permissions].
* You have saved and simulated the ILM policy.

CAUTION: Errors in an ILM policy can cause unrecoverable data loss. Carefully review and simulate the policy before activating it to confirm that it will work as intended. +
When you activate a new ILM policy, StorageGRID uses it to manage all objects, including existing objects and newly ingested objects. Before activating a new ILM policy, review any changes to the placement of existing replicated and erasure-coded objects. Changing an existing object's location might result in temporary resource issues when the new placements are evaluated and implemented.

.About this task

When you activate an ILM policy, the system distributes the new policy to all nodes. However, the new active policy might not actually take effect until all grid nodes are available to receive the new policy. In some cases, the system waits to implement a new active policy to ensure that grid objects aren't accidentally removed.

* If you make policy changes that increase data redundancy or durability, those changes are implemented immediately. For example, if you activate a new policy that includes a three-copies rule instead of a two-copies rule, that policy will be implemented right away because it increases data redundancy.
* If you make policy changes that could decrease data redundancy or durability, those changes will not be implemented until all grid nodes are available. For example, if you activate a new policy that uses a two-copies rule instead of a three-copies rule, the new policy will appear in the Active policy tab but it will not take effect until all nodes are online and available.

.Steps

. When you are ready to activate a policy, select *ILM* > *Policies*. On the Policies tab, select the checkbox for the policy you want to activate, then select *Activate*.
+
A warning message is displayed, prompting you to confirm that you want to activate the policy.

. When you have reviewed the details of the warning message and are sure the policy would manage data as expected, select *Activate policies*.

.Result

When a new ILM policy has been activated, the Policy state for the policy is changed to Active.

.Related information

link:example-6-changing-ilm-policy.html[Example 6: Changing an ILM policy]