---
permalink: ilm/manage-ilm-policy-tags.html
sidebar: sidebar
keywords: ILM policy tag
summary: 'You can view ILM policy tag details, edit a tag, or remove a tag.'
---
= Manage ILM policy tags
:icons: font
:imagesdir: ../media/

[.lead]
You can view ILM policy tag details, edit a tag, or remove a tag.

.Before you begin

* You are signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You have the link:../admin/admin-group-permissions.html[required access permissions].

== View ILM policy tag details

To view the details for a tag:

. Select *ILM* > *Policy tags*.
. Select the name of the policy from the table. The details page for the tag appears.

== Edit ILM policy tag

To edit the description for an existing tag:

. Select *ILM* > *Policy tags*.
. Select the checkbox for the tag, then select *Edit*.
+
Alternatively, select the name of the tag. The details page for the tag appears, and you can select *Edit* on that page. 
. Change the tag description as needed
. Select *Save*.

== Remove ILM policy tag

When you remove a policy tag, any buckets that are assigned that tag will be tagged with the Default policy tag.

To remove a tag:

. Select *ILM* > *Policy tags*.
. Select the checkbox for the tag, then select *Remove*. A confirmation dialog box appears.
+
Alternatively, select the name of the tag. The details page for the tag appears, and you can select *Remove* on that page. 
. Select *Yes* to delete the tag.